version: '3'

services:

  mysql:
    image: mysql:8.0.2
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - "./data:/var/lib/mysql:rw"
  
  keycloak:
    image: jboss/keycloak
    environment: 
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin 
    ports: 
      - "8080:8080"
